/**
 * Generated by plugforge/exporter/generate.js — do not edit by hand.
 * Personality: modern · accent: #00FFAA
 * UI↔APVTS bindings from plugforge/contracts/uiContract.js
 */

export type PluginParam = {
  id: string;
  name: string;
  min: number;
  max: number;
  def: number;
  unit?: string;
  type?: string;
  options?: string[];
  /** juce::NormalisableRange skew (1 = linear). */
  skew: number;
  /** Default in the same 0..1 domain as APVTS getValue()/setValue(). */
  defNormalised: number;
};

export type PluginFeatures = {
  spectrum: boolean;
  gainReduction: boolean;
  destructive: boolean;
  mainParamId: string;
  livingPlugin?: boolean;
  cloudPluginId?: string;
};

export type PluginConfig = {
  name: string;
  personality: string;
  accent: string;
  params: PluginParam[];
  features: PluginFeatures;
  uiContractVersion?: string;
};

export const PLUGIN_CONFIG: PluginConfig = {
  "name": "CelestialReverb",
  "personality": "modern",
  "accent": "#00FFAA",
  "params": [
    {
      "id": "reverbTime",
      "name": "Reverb Time",
      "min": 0.1,
      "max": 20,
      "def": 5,
      "unit": "s",
      "type": "knob",
      "skew": 1,
      "defNormalised": 0.2462311557788945
    },
    {
      "id": "gain",
      "name": "Output",
      "min": -24,
      "max": 24,
      "def": 0,
      "unit": "dB",
      "type": "knob",
      "skew": 1,
      "defNormalised": 0.5
    },
    {
      "id": "bypass",
      "name": "Bypass",
      "min": 0,
      "max": 1,
      "def": 0,
      "unit": "",
      "type": "toggle",
      "skew": 1,
      "defNormalised": 0
    }
  ],
  "features": {
    "spectrum": true,
    "gainReduction": false,
    "destructive": false,
    "mainParamId": "gain",
    "livingPlugin": true,
    "cloudPluginId": "com.pearlleash.celestialreverb"
  },
  "uiContractVersion": "1.0.0"
};
